# =============================================================================
# TAL MONITOR CONFIGURATION
# Target Account List — 304 named accounts to watch for any signal.
# Territory rules do NOT apply here. Every company on this list is monitored
# regardless of where it is headquartered.
#
# To add a company: copy any entry format below and add it to ACCOUNTS.
# To remove: delete the line or comment it out with #
# Changes deploy automatically within 2 minutes of a GitHub commit.
# =============================================================================


# ---------------------------------------------------------------------------
# POLLING INTERVALS
# ---------------------------------------------------------------------------

# How often to check Google News for each batch of companies (seconds)
# 304 companies checked in batches of 10 = ~31 batches per cycle
# At 1 request/second that's ~31 seconds per cycle
POLL_INTERVAL_SECONDS = 3600   # full sweep every 60 minutes

# Website change detection runs less frequently (every 4 hours)
# to avoid hammering company servers
WEBSITE_CHECK_INTERVAL_SECONDS = 14400


# ---------------------------------------------------------------------------
# DISCORD
# Separate channel from the open market monitors.
# All TAL alerts go to #accounts regardless of score.
# High-urgency signals (score 8+) get an @here mention.
# ---------------------------------------------------------------------------

URGENT_SCORE_THRESHOLD = 8   # score 8+ triggers @here mention


# ---------------------------------------------------------------------------
# GOOGLE NEWS
# Free RSS feed — no API key required.
# Searches: news.google.com/rss/search?q="Company+Name"
# ---------------------------------------------------------------------------

# How many results to check per company per cycle (Google News returns up to 10)
NEWS_RESULTS_PER_COMPANY = 5

# Only alert on news published within this many hours
NEWS_LOOKBACK_HOURS = 25   # slightly over 24 to avoid gaps


# ---------------------------------------------------------------------------
# TARGET ACCOUNT LIST — 304 companies
# Fields: name, website, industry, subindustry, city, state
# ---------------------------------------------------------------------------

ACCOUNTS = [
    {"name": "LEMCO Precision", "website": "http://www.lemcoprecision.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Upland", "state": "CA"},
    {"name": "Bow Wow Labs", "website": "https://www.bowwowlabs.com", "industry": "Manufacturing", "subindustry": "Pet Products", "city": "Austin", "state": "TX"},
    {"name": "Gleckler & Sons Construction", "website": "http://www.glecklerandsons.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "Jacksonville", "state": "FL"},
    {"name": "LivingWell", "website": "http://www.livingwellabc.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Silver Spring", "state": "MD"},
    {"name": "Qcify", "website": "http://www.qcify.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "San Mateo", "state": "CA"},
    {"name": "Six15 Technologies", "website": "http://six-15.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Henrietta", "state": "NY"},
    {"name": "Motto Beverage Company", "website": "http://drinkmotto.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "New York", "state": "NY"},
    {"name": "Defi Snacks", "website": "https://www.defi-snacks.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Chatham", "state": "NJ"},
    {"name": "Vom Fass USA", "website": "http://www.vomfassusa.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Madison", "state": "WI"},
    {"name": "TDL International", "website": "http://www.tdlintcorp.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Medley", "state": "FL"},
    {"name": "Patak Spices", "website": "http://www.pataksusa.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Clearwater", "state": "FL"},
    {"name": "Piggly Wiggly Franchise", "website": "https://pigglywigglysneadsfl.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Sneads", "state": "FL"},
    {"name": "Savia USA", "website": "https://saviausa.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Tampa", "state": "FL"},
    {"name": "VT Artisan Coffee & Tea Co", "website": "http://www.vtartisan.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Waterbury", "state": "VT"},
    {"name": "Newark Natural Foods", "website": "http://www.newarknaturalfoods.com", "industry": "Retail", "subindustry": "Vitamins, Supplements & Health Stores", "city": "Newark", "state": "DE"},
    {"name": "Titan Foods Inc.", "website": "http://www.titanfoods.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Astoria", "state": "NY"},
    {"name": "Casa Foods", "website": "http://www.casafoods.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Middleton", "state": "MA"},
    {"name": "NFADA Wholesale Distributors", "website": "http://www.nfadawd.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Williamsville", "state": "NY"},
    {"name": "Frsesh Victor", "website": "http://freshvictor.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "San Francisco", "state": "CA"},
    {"name": "Versatrim, LLC", "website": "http://www.versatrim.com", "industry": "Retail", "subindustry": "Home Improvement & Hardware Retail", "city": "Henderson", "state": "NC"},
    {"name": "Surgical Direct", "website": "https://www.surgicaldirect.com", "industry": "Retail", "subindustry": "Vitamins, Supplements & Health Stores", "city": "", "state": "FL"},
    {"name": "Countrypet Naturals, LLC", "website": "http://www.countrypet.com", "industry": "Manufacturing", "subindustry": "Pet Products", "city": "Manchester", "state": "CT"},
    {"name": "Mighty Missouri Coffee", "website": "http://www.mightymissouri.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Bismarck", "state": "ND"},
    {"name": "Webb's Machinery", "website": "https://www.webbsmachinery.com", "industry": "Retail", "subindustry": "Home Improvement & Hardware Retail", "city": "Vegreville", "state": "AB"},
    {"name": "Sweet Nothings Inc.", "website": "http://www.eatsweetnothings.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Menlo Park", "state": "CA"},
    {"name": "Cocoa Dolce Chocolates LLC", "website": "https://cocoadolce.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Wichita", "state": "KS"},
    {"name": "Sunnie, Inc.", "website": "http://www.sunniesnacks.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Los Angeles", "state": "CA"},
    {"name": "West Tech Materials", "website": "http://westechmat.com", "industry": "Retail", "subindustry": "Vitamins, Supplements & Health Stores", "city": "Costa Mesa", "state": "CA"},
    {"name": "Janey Lou's", "website": "http://www.janeylous.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Salt Lake City", "state": "UT"},
    {"name": "Cogency Group", "website": "https://cogencyg.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Duluth", "state": "GA"},
    {"name": "Titan Florida Doors(Titan Building Supply)", "website": "http://titanfloridadoors.com", "industry": "Retail", "subindustry": "Home Improvement & Hardware Retail", "city": "", "state": "FL"},
    {"name": "Coble Holdings", "website": "http://CobleHoldingsdummy.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Tampa", "state": "FL"},
    {"name": "OMATS Brands LLC", "website": "http://omats.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Delray Beach", "state": "FL"},
    {"name": "Trumpdrive Energy", "website": "https://trumpdriveenergy.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Boca Raton", "state": "FL"},
    {"name": "Oneonta Equipment Rental and Sales", "website": "https://oneontaequipment.net", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Oneonta", "state": "NY"},
    {"name": "Versatile Products and Ingredients, LLC", "website": "http://www.versatileingredients.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Chestnut Ridge", "state": "NY"},
    {"name": "Vmi Sports", "website": "http://www.vmisports.com", "industry": "Retail", "subindustry": "Vitamins, Supplements & Health Stores", "city": "Syosset", "state": "NY"},
    {"name": "Wake Up Water", "website": "https://drinkwakeupwater.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Boston", "state": "MA"},
    {"name": "Perrone & Sons Inc.", "website": "http://www.perroneandsons.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Metairie", "state": "LA"},
    {"name": "S4 Medical", "website": "http://www.s4medical.com", "industry": "Retail", "subindustry": "Vitamins, Supplements & Health Stores", "city": "Cleveland", "state": "OH"},
    {"name": "MG Spices", "website": "https://mgspicesco.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Mentor", "state": "OH"},
    {"name": "Addilan Group", "website": "https://addilangroup.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Norristown", "state": "PA"},
    {"name": "Elves Co", "website": "http://elvesco.com", "industry": "Retail", "subindustry": "Home Improvement & Hardware Retail", "city": "", "state": "GA"},
    {"name": "Fluid Hose & Coupling Inc", "website": "http://www.fluidhose.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Hamilton", "state": "ON"},
    {"name": "Taste of Maine LLC", "website": "https://tasteofmaine.net", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Limestone", "state": "ME"},
    {"name": "One Off Robotics", "website": "http://oneoffrobotics.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Chattanooga", "state": "TN"},
    {"name": "The Board Smith", "website": "https://theboardsmith.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "Plano", "state": "TX"},
    {"name": "Happy Moose Juice", "website": "http://happymoosejuice.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "San Francisco", "state": "CA"},
    {"name": "National Bioskills Laboratories", "website": "http://www.nationalbioskills.com", "industry": "Retail", "subindustry": "Vitamins, Supplements & Health Stores", "city": "Dallas", "state": "TX"},
    {"name": "Sour Milk", "website": "https://www.sourmilk.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "New York", "state": "NY"},
    {"name": "Rogers Collection", "website": "http://www.rogerscollection.us", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Portland", "state": "ME"},
    {"name": "Almost Famous Popcorn", "website": "http://www.crpopcorn.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Cedar Rapids", "state": "IA"},
    {"name": "Fernson Brewing", "website": "http://www.fernson.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Sioux Falls", "state": "SD"},
    {"name": "Anchor Dock & Lift Inc", "website": "http://www.anchor-dock.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Annandale", "state": "MN"},
    {"name": "TapRm", "website": "http://www.taprm.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "New York", "state": "NY"},
    {"name": "Shock Coffee LLC", "website": "http://www.shockcoffee.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Woodside", "state": "NY"},
    {"name": "Penn Tool", "website": "http://www.penntoolco.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Maplewood", "state": "NJ"},
    {"name": "Common Room Roasters", "website": "http://www.commonroomroasters.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Newport Beach", "state": "CA"},
    {"name": "Fireball Tool", "website": "http://www.fireballtool.com", "industry": "Retail", "subindustry": "Home Improvement & Hardware Retail", "city": "Spokane", "state": "WA"},
    {"name": "EquiLife Inc", "website": "http://www.equi.life", "industry": "Retail", "subindustry": "Vitamins, Supplements & Health Stores", "city": "Boston", "state": "MA"},
    {"name": "Hydro One Premium Beverages, LLC", "website": "http://hydroonebeverages.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Greenwood", "state": "SC"},
    {"name": "Trans-Continental Manufacturing", "website": "http://www.t-cmfg.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "San Diego", "state": "CA"},
    {"name": "Tomahawk Shades", "website": "http://www.tomahawkshades.com", "industry": "Retail", "subindustry": "Home Improvement & Hardware Retail", "city": "Farmingdale", "state": "NY"},
    {"name": "All Parts Machinery", "website": "https://allparts.expert", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "", "state": "FL"},
    {"name": "Anka Foods", "website": "https://ankafoods.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Fairfield", "state": "NJ"},
    {"name": "Gia Foods Ltd", "website": "http://giafoods.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Burnaby", "state": "BC"},
    {"name": "nemesis coffee", "website": "http://nemesis.coffee", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Vancouver", "state": "BC"},
    {"name": "Copan Trade", "website": "http://www.copantrade.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Magnolia", "state": "TX"},
    {"name": "Kelyniam Global, Inc", "website": "http://www.kelyniam.com", "industry": "Retail", "subindustry": "Vitamins, Supplements & Health Stores", "city": "Collinsville", "state": "CT"},
    {"name": "Mull-It-Over Products", "website": "http://www.mullitoverproducts.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "Grandville", "state": "MI"},
    {"name": "Power Equipment Plus", "website": "http://www.powerequipmentplus1.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Southampton", "state": "NY"},
    {"name": "Stainless Software", "website": "http://www.stainlessapi.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "Brooklyn", "state": "NY"},
    {"name": "Northern Stone Supply, Inc.", "website": "https://northernstonesupply.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "Oakley", "state": "ID"},
    {"name": "PK Industrial Supply", "website": "http://www.pkindsupply.net", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Baytown", "state": "TX"},
    {"name": "Peachtree Foods", "website": "https://www.peachtreefoods.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Peachtree Corners", "state": "GA"},
    {"name": "Mill Creek Brands", "website": "http://www.millcreekbrands.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Nolensville", "state": "TN"},
    {"name": "Silesia Flavors, Inc.", "website": "http://www.silesia-aroma.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Hoffman Estates", "state": "IL"},
    {"name": "Thierica", "website": "http://www.thierica.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Grand Rapids", "state": "MI"},
    {"name": "EDV International", "website": "http://www.edvinter.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Columbus", "state": "OH"},
    {"name": "Brewlando", "website": "http://www.brewlando.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Orlando", "state": "FL"},
    {"name": "Top Notch Dock & Door DBA US Dock & Door", "website": "http://usdockdoor.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "", "state": "GA"},
    {"name": "Huxley & Kent", "website": "http://www.huxleyandkent.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Knoxville", "state": "TN"},
    {"name": "Ramos Marble & Granite", "website": "http://www.rmg-inc.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "Tampa", "state": "FL"},
    {"name": "The Champions Group", "website": "http://www.chmpgrp.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Houston", "state": "TX"},
    {"name": "Milby Company", "website": "http://www.milbycompany.com", "industry": "Retail", "subindustry": "Home Improvement & Hardware Retail", "city": "", "state": "MD"},
    {"name": "MidSouth Forestry Equipment", "website": "https://www.midsouthforestryequip.com/about.htm", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Warren", "state": "AR"},
    {"name": "Scruggs Co., Inc.", "website": "http://www.scruggsco.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "Houston", "state": "TX"},
    {"name": "Professional Pallets", "website": "http://www.professionalpallets.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "Lawrenceburg", "state": "IN"},
    {"name": "North American Precision Metals", "website": "http://www.napm-inc.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Fort Worth", "state": "TX"},
    {"name": "Gauntlet AI", "website": "https://www.gauntletai.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Austin", "state": "TX"},
    {"name": "Leap Surgical DBA Leap Distributors", "website": "https://leapdistributors.com", "industry": "Retail", "subindustry": "Vitamins, Supplements & Health Stores", "city": "Dallas", "state": "TX"},
    {"name": "Certus Manufacturing", "website": "http://certusmfg.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Saint Paul", "state": "MN"},
    {"name": "Elevate Health Technologies", "website": "https://www.elevateht.com", "industry": "Retail", "subindustry": "Vitamins, Supplements & Health Stores", "city": "Houston", "state": "TX"},
    {"name": "Powerstick.com", "website": "http://www.powerstick.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Ottawa", "state": "ON"},
    {"name": "Southstream Seafoods", "website": "http://www.southstream.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Warwick", "state": "RI"},
    {"name": "Sage Product Development Inc.", "website": "http://www.sagepd.com", "industry": "Retail", "subindustry": "Vitamins, Supplements & Health Stores", "city": "Foxborough", "state": "MA"},
    {"name": "Based Body Works", "website": "http://basedbodyworks.com", "industry": "Retail", "subindustry": "Vitamins, Supplements & Health Stores", "city": "Los Altos", "state": "CA"},
    {"name": "Continental Food and Beverage", "website": "https://incakolausa.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Clifton", "state": "NJ"},
    {"name": "Nasiff Fruit Company", "website": "https://www.nasiffproduce.com/pages/cfHome.cfm", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Fall River", "state": "MA"},
    {"name": "Prime Drink Group Corp", "website": "http://prime-group.ca", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Montreal", "state": "QC"},
    {"name": "My Better Batch", "website": "http://www.mybetterbatch.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Kernersville", "state": "NC"},
    {"name": "Northland Lawn, Sport & Equipment", "website": "https://www.mynorthland.com", "industry": "Retail", "subindustry": "Home Improvement & Hardware Retail", "city": "Mason", "state": "WI"},
    {"name": "Central Standard Craft Distillery", "website": "http://www.thecentralstandard.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Milwaukee", "state": "WI"},
    {"name": "Walston Architectural Products", "website": "https://walstonarchitecturalproducts.com/collections/all", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "North Kansas City", "state": "MO"},
    {"name": "Phoenix Door Systems", "website": "http://www.phoenixdoorsystems.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "Mason", "state": "OH"},
    {"name": "Zenith Technical Innovations", "website": "http://www.thermxtherapy.com", "industry": "Retail", "subindustry": "Vitamins, Supplements & Health Stores", "city": "Gurnee", "state": "IL"},
    {"name": "MetalFab Guys", "website": "http://www.metalfabguys.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "Walker", "state": "LA"},
    {"name": "Jubilee Specialty Wood Products", "website": "http://www.jubileeswp.com", "industry": "Retail", "subindustry": "Home Improvement & Hardware Retail", "city": "Mobile", "state": "AL"},
    {"name": "Belfi Brothers & Company, Inc.", "website": "http://www.belfibrothers.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "Philadelphia", "state": "PA"},
    {"name": "MPAQ Automation Inc.", "website": "http://www.mpaq.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Mississauga", "state": "ON"},
    {"name": "Trace Oats", "website": "http://tracesoats.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Nashville", "state": "TN"},
    {"name": "Gunthers Building Center", "website": "http://www.gunthers.net", "industry": "Retail", "subindustry": "Home Improvement & Hardware Retail", "city": "Calgary", "state": "AB"},
    {"name": "Weiss Acquisition, LLC", "website": "http://weissindustrial.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Pittsburgh", "state": "PA"},
    {"name": "Royal Dental Group", "website": "https://royaldentalgroup.com", "industry": "Retail", "subindustry": "Vitamins, Supplements & Health Stores", "city": "Everett", "state": "WA"},
    {"name": "Marks Snacks", "website": "https://markssnacks.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "", "state": "CA"},
    {"name": "Be Fish Wholesale Sushi (Formerly Bumblefish Sushi)", "website": "https://www.be.fish", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Kansas City", "state": "MO"},
    {"name": "ATS Cases, Inc", "website": "http://www.atscases.com", "industry": "Retail", "subindustry": "Vitamins, Supplements & Health Stores", "city": "Northborough", "state": "MA"},
    {"name": "Success Import USA Inc", "website": "http://www.successfoodusa.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Ontario", "state": "CA"},
    {"name": "Pacific Roller Die Co", "website": "http://www.prdcompany.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Hayward", "state": "CA"},
    {"name": "Cross Industry Dynamics", "website": "http://www.crossindustrydynamics.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "Westminster", "state": "CO"},
    {"name": "Admiral Engineering & Manufacturing", "website": "http://www.admiraleng.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Phoenix", "state": "AZ"},
    {"name": "Cooking Panda", "website": "http://www.cookingpanda.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Canoga Park", "state": "CA"},
    {"name": "Manthei Wood Products", "website": "https://www.mantheiwoodproducts.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "Petoskey", "state": "MI"},
    {"name": "Hundredweight Ice", "website": "http://www.hundredweightice.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Long Island City", "state": "NY"},
    {"name": "Systems with Intelligence", "website": "http://www.systemswithintelligence.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Mississauga", "state": "ON"},
    {"name": "Energy Valve and Supply Company, LLC", "website": "http://envasco.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Houston", "state": "TX"},
    {"name": "Coapt, LLC", "website": "http://www.coaptengineering.com", "industry": "Retail", "subindustry": "Vitamins, Supplements & Health Stores", "city": "Chicago", "state": "IL"},
    {"name": "Koffe Kult", "website": "https://www.koffeekult.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Hollywood", "state": "FL"},
    {"name": "Newton CFV", "website": "https://newtoncfv.com", "industry": "Retail", "subindustry": "Home Improvement & Hardware Retail", "city": "Sebastian", "state": "FL"},
    {"name": "Abe's Muffins", "website": "http://www.abesmuffins.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "West Nyack", "state": "NY"},
    {"name": "ALL AMERICAN SYSTEMS", "website": "https://www.allamericansystems.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Aurora", "state": "IL"},
    {"name": "Co2 Refrigeration Systems", "website": "http://co2refsystems.com", "industry": "Retail", "subindustry": "Home Improvement & Hardware Retail", "city": "", "state": "IA"},
    {"name": "Midstate Industrial", "website": "http://www.midstateind.net", "industry": "Retail", "subindustry": "Vitamins, Supplements & Health Stores", "city": "Kennesaw", "state": "GA"},
    {"name": "Clover hill", "website": "http://www.9851519cloverhill.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Breinigsville", "state": "PA"},
    {"name": "Avalon Dairy", "website": "https://www.avalondairy.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Burnaby", "state": "BC"},
    {"name": "Fraserview Cedar Products Ltd", "website": "http://www.fraserviewcedar.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "Surrey", "state": "BC"},
    {"name": "Olivia's Crouton Company, Inc.", "website": "http://www.oliviascroutons.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "New Haven", "state": "VT"},
    {"name": "Miami Growth Machine", "website": "http://www.miamigrowthmachine.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "Miami", "state": "FL"},
    {"name": "NAVAC", "website": "https://navacglobal.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "Lyndhurst", "state": "NJ"},
    {"name": "Right Coast Medical", "website": "http://www.rightcoastmedical.com", "industry": "Retail", "subindustry": "Vitamins, Supplements & Health Stores", "city": "Johnson City", "state": "TN"},
    {"name": "Fabrication Automation", "website": "https://fabricationautomation.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Concord", "state": "NC"},
    {"name": "Shata Traders Inc.", "website": "https://threeriversfoods.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Brooklyn", "state": "NY"},
    {"name": "Regalia Coffee", "website": "http://www.regaliacoffee.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Long Island City", "state": "NY"},
    {"name": "Nature's Best", "website": "http://natures.best", "industry": "Retail", "subindustry": "Grocery Retail", "city": "New York City", "state": "NY"},
    {"name": "Sigma Engineered Solutions", "website": "http://www.sigmaengineeredsolutions.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Garner", "state": "NC"},
    {"name": "Atlas Medical, Inc.", "website": "http://www.atlasequipped.com", "industry": "Retail", "subindustry": "Vitamins, Supplements & Health Stores", "city": "Richmond", "state": "VA"},
    {"name": "Sugar Ghost Ice Cream and Bubble Tea", "website": "https://www.sugarghostmemphis.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Memphis", "state": "TN"},
    {"name": "Trilogy Machinery", "website": "https://HTTP://www.trilogymachinery.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Belcamp", "state": "MD"},
    {"name": "North American Safety Products Inc", "website": "http://www.naspinc.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Frankfort", "state": "IL"},
    {"name": "Fluid Transfer Systems, Inc.", "website": "http://www.ftsonline.net", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Novi", "state": "MI"},
    {"name": "TOBROCO MACHINERY LLC", "website": "https://giantloaders.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Des Moines", "state": "IA"},
    {"name": "Bruno'S Iron & Metal, L.P.", "website": "https://brunosrecycling.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Fresno", "state": "CA"},
    {"name": "MD Tooling", "website": "https://mdtooling.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Howell", "state": "MI"},
    {"name": "Up & S, Inc.", "website": "http://www.up-s.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "Odessa", "state": "TX"},
    {"name": "Kace Valves", "website": "https://kacevalves.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Sugar Land", "state": "TX"},
    {"name": "Vulpes Industrial", "website": "http://www.vulpesindustrial.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "St. Louis", "state": "MO"},
    {"name": "Wesclean Northern Sales Ltd", "website": "https://www.wescleannwt.com", "industry": "Retail", "subindustry": "Home Improvement & Hardware Retail", "city": "Hay River", "state": "NT"},
    {"name": "Top Note Tonics", "website": "https://store.topnotetonic.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Milwaukee", "state": "WI"},
    {"name": "The Supply Post Newspaper", "website": "http://www.supplypost.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Langley", "state": "BC"},
    {"name": "American Wholesale Co.", "website": "https://americanwholesaleco.com", "industry": "Retail", "subindustry": "Home Improvement & Hardware Retail", "city": "Sacramento", "state": "CA"},
    {"name": "Smarter Alloys", "website": "http://www.smarteralloys.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "Waterloo", "state": "ON"},
    {"name": "Everest Metals Inc", "website": "http://www.everestmetalsinc.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "Oakland", "state": "IA"},
    {"name": "Prime Executions, Inc., d/b/a Freedom Capital Markets", "website": "http://www.freedomcapmkts.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "New York", "state": "NY"},
    {"name": "Amtrade Inc", "website": "http://www.amtradeinc.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "New York City", "state": "NY"},
    {"name": "Bobbysue's Nuts", "website": "http://www.bobbysuesnuts.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Chappaqua", "state": "NY"},
    {"name": "Sherman Specialty Company", "website": "http://shermandental.com", "industry": "Retail", "subindustry": "Home Improvement & Hardware Retail", "city": "Syosset", "state": "NY"},
    {"name": "Moment", "website": "https://www.shopmoment.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Seattle", "state": "WA"},
    {"name": "Performance Windows & Exteriors", "website": "http://www.goperformancewindows.com", "industry": "Retail", "subindustry": "Home Improvement & Hardware Retail", "city": "Rapid City", "state": "SD"},
    {"name": "felt right", "website": "http://www.feltright.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "Salt Lake City", "state": "UT"},
    {"name": "Patagonia Distribution", "website": "http://www.patagoniadistribution.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Miami", "state": "FL"},
    {"name": "San Bernardo Ice Cream", "website": "http://sanbernardoicecream.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Miramar", "state": "FL"},
    {"name": "PAX Spices and Labs, Inc.", "website": "http://www.paxspices.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Covina", "state": "CA"},
    {"name": "Ultra Stones Llc", "website": "http://www.ultrastones.com", "industry": "Retail", "subindustry": "Home Improvement & Hardware Retail", "city": "Farmingdale", "state": "NY"},
    {"name": "Veon Inc. (Adaptive Mobility Solutions)", "website": "https://amslifts.com", "industry": "Retail", "subindustry": "Vitamins, Supplements & Health Stores", "city": "Washington", "state": "NC"},
    {"name": "Standup AI", "website": "https://standupai.com", "industry": "Retail", "subindustry": "Home Improvement & Hardware Retail", "city": "", "state": "DE"},
    {"name": "A & W Devices, Inc", "website": "http://a-w-devices.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Pine Grove", "state": "CA"},
    {"name": "Richard's Rainwater, Inc.", "website": "http://www.richardsrainwater.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Dripping Springs", "state": "TX"},
    {"name": "Rolfes at Boone", "website": "http://www.rolfesatboone.com", "industry": "Retail", "subindustry": "Home Improvement & Hardware Retail", "city": "Boone", "state": "IA"},
    {"name": "Origine Nature", "website": "https://originenature.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "", "state": "QC"},
    {"name": "R.A. Graham Co. Inc.", "website": "http://www.ragraham.com", "industry": "Retail", "subindustry": "Home Improvement & Hardware Retail", "city": "Rochdale", "state": "MA"},
    {"name": "Still Life Frozen Fruit", "website": "https://eatfrozenfruit.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Los Angeles", "state": "CA"},
    {"name": "NERD Beverage Corporation", "website": "http://www.nerdfocus.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Roanoke", "state": "VA"},
    {"name": "ARC Products Global", "website": "http://www.arcproductsglobal.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Spartanburg", "state": "SC"},
    {"name": "Siena, LLC", "website": "http://www.sienausa.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "Washington", "state": "DC"},
    {"name": "Doral International Foods, LLC", "website": "https://www.doralfoods.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Miami", "state": "FL"},
    {"name": "Corestock Industrial Supply", "website": "http://www.corestock.ca", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Prince George", "state": "BC"},
    {"name": "United Spas MFG LLC", "website": "https://unitedspasmfg.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "Salina", "state": "CA"},
    {"name": "Rashmi's Bakery", "website": "https://www.rashmisbakery.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Brampton", "state": "ON"},
    {"name": "James Steel & Tube Company", "website": "http://www.jamessteel.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "Madison Heights", "state": "MI"},
    {"name": "Maurice Pincoffs Company, Inc.", "website": "http://www.pincoffs.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Houston", "state": "TX"},
    {"name": "Stratus Vineyards and Teknion Corporation", "website": "http://www.stratuswines.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Niagara-On-The-Lake", "state": "ON"},
    {"name": "Greenheck Group", "website": "https://greenheckgroup.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "Schofield", "state": "WI"},
    {"name": "Central Texas Equipment", "website": "http://www.ctegroup.net", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Austin", "state": "TX"},
    {"name": "Prismecs", "website": "http://www.prismecs.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Houston", "state": "TX"},
    {"name": "Nancy's Candy Company, LLC", "website": "http://nancyshomemadefudge.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Meadows Of Dan", "state": "VA"},
    {"name": "Spartan Composites", "website": "http://www.spartancomposites.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Rockledge", "state": "FL"},
    {"name": "RAJ SUPPLY", "website": "http://www.rajsupply.com", "industry": "Retail", "subindustry": "Home Improvement & Hardware Retail", "city": "Crystal River", "state": "FL"},
    {"name": "Holey Grail Donuts", "website": "https://www.holeygraildonuts.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Hanalei", "state": "HI"},
    {"name": "BALLISTIGLASS", "website": "http://www.ballistiglass.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "Parkland", "state": "FL"},
    {"name": "Solbasium", "website": "http://www.solbasium.com", "industry": "Retail", "subindustry": "Vitamins, Supplements & Health Stores", "city": "", "state": "VA"},
    {"name": "Juliet", "website": "http://www.drinkjuliet.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "New York", "state": "NY"},
    {"name": "Fort Garry Brewing", "website": "https://fortgarry.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Winnipeg", "state": "MB"},
    {"name": "POSHI", "website": "http://www.poshi.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Miami", "state": "FL"},
    {"name": "Standard Bots", "website": "http://standardbots.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Glen Cove", "state": "NY"},
    {"name": "Curio Spice Co.", "website": "http://www.curiospice.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Cambridge", "state": "MA"},
    {"name": "Industrial Spring", "website": "http://www.isckc.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Kansas City", "state": "MO"},
    {"name": "Bombora Gear", "website": "http://www.bomboragear.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Pembroke", "state": "MA"},
    {"name": "A&R Packing", "website": "http://www.arpackingco.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Livonia", "state": "MI"},
    {"name": "National Stabilizers Inc", "website": "http://nationalstabilizers.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Azusa", "state": "CA"},
    {"name": "Zenwise Health LLC", "website": "http://www.zenwise.com", "industry": "Retail", "subindustry": "Vitamins, Supplements & Health Stores", "city": "Wilmington", "state": "DE"},
    {"name": "Dr. Stolberg", "website": "https://doctorstolberg.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Los Angeles", "state": "CA"},
    {"name": "Purity Coffee Inc", "website": "http://puritycoffee.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Greenville", "state": "SC"},
    {"name": "We Are The New farmers", "website": "http://www.new-farmers.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Brooklyn", "state": "NY"},
    {"name": "Saltwater Coffee", "website": "http://www.saltwaternyc.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "New York", "state": "NY"},
    {"name": "Algio Produce LLC", "website": "http://www.algioproduce.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Wilmington", "state": "DE"},
    {"name": "Home Value Store II", "website": "http://www.myhomevaluestore.com", "industry": "Retail", "subindustry": "Home Improvement & Hardware Retail", "city": "Fort Lauderdale", "state": "FL"},
    {"name": "Richmond Decorating Center", "website": "http://www.richmonddecorating.com", "industry": "Retail", "subindustry": "Home Improvement & Hardware Retail", "city": "Richmond", "state": "VA"},
    {"name": "Fastech", "website": "http://fastech-engineering.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Virginia Beach", "state": "VA"},
    {"name": "Masas Usa, Inc.", "website": "https://www.masasusa.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "East Haven", "state": "CT"},
    {"name": "Poppin Cobs", "website": "http://www.poppincobs.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Flora", "state": "IN"},
    {"name": "Fruitealicious", "website": "http://www.fruitealicious.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Plano", "state": "TX"},
    {"name": "all temp windows - Kudzu Millwork Inc.", "website": "http://www.alltempwindows.com", "industry": "Retail", "subindustry": "Home Improvement & Hardware Retail", "city": "Rainsville", "state": "AL"},
    {"name": "Better Bites Bakery", "website": "http://www.betterbitesbakery.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Austin", "state": "TX"},
    {"name": "Secure Door and Hardware, LLC", "website": "http://securedoorandhardware.com/products-services", "industry": "Retail", "subindustry": "Home Improvement & Hardware Retail", "city": "Trainer", "state": "PA"},
    {"name": "Berliner Specialty Distributors", "website": "http://www.berlinerfoods.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "HYATTSVILLE", "state": "MD"},
    {"name": "Dynamis Power Solutions, LLC", "website": "http://www.dynamisps.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "The Woodlands", "state": "TX"},
    {"name": "Guide Valve Limited", "website": "https://www.gvs-vci.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Woodbridge", "state": "ON"},
    {"name": "Ebars LLC", "website": "http://www.ebars.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Franklin", "state": "TN"},
    {"name": "EH Teasley", "website": "http://ehteasley.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Dallas", "state": "TX"},
    {"name": "Tompkins Industries, Inc.", "website": "http://www.tompkinsind.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "New Castle", "state": "DE"},
    {"name": "Big Country Organic Brewing Co.", "website": "https://enjoybigcountry.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Pflugerville", "state": "TX"},
    {"name": "Site Drainer, LLC", "website": "http://www.sitedrainer.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Clifton", "state": "NJ"},
    {"name": "Cache River Mill and MetalWorks", "website": "http://www.cacherivermill.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Little Rock", "state": "AR"},
    {"name": "Portland Compressor Inc", "website": "http://www.portlandcompressor.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Portland", "state": "OR"},
    {"name": "Chisholm Trail Redi Mix, LLC.", "website": "https://www.chisholmtrailredimix.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "Cleburne", "state": "TX"},
    {"name": "East Coast Wild Blueberry", "website": "http://www.cranberryfarm.ca", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Sackville", "state": "NB"},
    {"name": "HITE Services Ltd", "website": "http://www.hiteservices.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Sudbury", "state": "ON"},
    {"name": "T-Quip Sales & Rentals", "website": "http://tquip.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Londonderry", "state": "NH"},
    {"name": "The Conking & Calabrese Co. Inc", "website": "http://www.conkingandcalabrese.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "Fairport", "state": "NY"},
    {"name": "Magnum Forest Products", "website": "http://magnumforestproducts.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "", "state": "MB"},
    {"name": "The Breastfeeding Shop", "website": "http://thebreastfeedingshop.com", "industry": "Retail", "subindustry": "Vitamins, Supplements & Health Stores", "city": "Emmaus", "state": "PA"},
    {"name": "Aqua Theon", "website": "http://www.aquatheon.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Pacifica", "state": "CA"},
    {"name": "BioAssay Works LLC", "website": "http://www.bioassayworks.com", "industry": "Retail", "subindustry": "Vitamins, Supplements & Health Stores", "city": "Ijamsville", "state": "MD"},
    {"name": "NuttZo", "website": "https://www.nuttzo.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "San Diego", "state": "CA"},
    {"name": "chipz Happen", "website": "https://chipzhappen.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "La Mesa", "state": "CA"},
    {"name": "Nonaste", "website": "https://nonaste.com", "industry": "Retail", "subindustry": "Vitamins, Supplements & Health Stores", "city": "New York", "state": "NY"},
    {"name": "Firefly Photonics, LLC", "website": "http://fireflyphotonics.com", "industry": "Retail", "subindustry": "Vitamins, Supplements & Health Stores", "city": "Coralville", "state": "IA"},
    {"name": "Wisconsin River Brands Inc", "website": "https://www.wisconsinrivermeats.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Mauston", "state": "WI"},
    {"name": "WIN Nutrition", "website": "http://winutrition.com", "industry": "Retail", "subindustry": "Vitamins, Supplements & Health Stores", "city": "Mount Bethel", "state": "PA"},
    {"name": "G.O.A.T Fuel", "website": "http://www.goatfuel.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Plano", "state": "TX"},
    {"name": "Jireh Packing Company", "website": "http://jirehcompanies.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "", "state": "CA"},
    {"name": "Belco Forest Products", "website": "http://belcofp.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "Shelton", "state": "WA"},
    {"name": "Country Bob's", "website": "http://www.countrybobs.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Centralia", "state": "IL"},
    {"name": "Drafft Root Beer Inc", "website": "http://www.drafft.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Dallas", "state": "TX"},
    {"name": "General Sheet Metal", "website": "http://www.gsmw.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "Clackamas", "state": "OR"},
    {"name": "Yak9 Chews", "website": "http://www.yak9chews.com", "industry": "Manufacturing", "subindustry": "Pet Products", "city": "Cedar Park", "state": "TX"},
    {"name": "Pioneer Machine Sales", "website": "http://www.pioneermachinesales.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Houston", "state": "TX"},
    {"name": "CoFi Inc", "website": "http://www.cofimd.com", "industry": "Retail", "subindustry": "Vitamins, Supplements & Health Stores", "city": "Holliston", "state": "MA"},
    {"name": "Secret Aardvark", "website": "http://www.secretaardvark.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Oregon City", "state": "OR"},
    {"name": "Moku Foods", "website": "http://mokufoods.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Los Angeles", "state": "CA"},
    {"name": "SAVRpak", "website": "http://www.savrpak.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "San Juan", "state": "CA"},
    {"name": "Bhakti Chai", "website": "https://drinkbhakti.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Boulder", "state": "CO"},
    {"name": "Ready Set Food", "website": "http://www.readysetfood.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Encino", "state": "CA"},
    {"name": "Sosi's Healthy Pleasures", "website": "http://www.sosishealthypleasures.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Aurora", "state": "CO"},
    {"name": "Polidori Sausage", "website": "http://www.polidorisausage.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Denver", "state": "CO"},
    {"name": "Umaro Foods", "website": "http://umarofoods.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Albany", "state": "CA"},
    {"name": "Maintecx Machine Tools", "website": "http://maintecx.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Minneapolis", "state": "MN"},
    {"name": "Dinamec Systems", "website": "http://www.dinamecsystems.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Acworth", "state": "GA"},
    {"name": "3051850 Ontario Limited", "website": "http://aegdesigns.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Egbert", "state": "ON"},
    {"name": "Curto-Ligonier Foundries Co.", "website": "https://curto.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "Melrose Park", "state": "IL"},
    {"name": "Golden Rule Signs, LLC", "website": "http://schoolmarquee.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Louisville", "state": "KY"},
    {"name": "Wholesale Door Supply", "website": "http://www.wholesaledoorsupply.com", "industry": "Retail", "subindustry": "Home Improvement & Hardware Retail", "city": "Elizabethtown", "state": "KY"},
    {"name": "Nuvo Olive Oil", "website": "http://www.nuvooliveoil.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Costa Mesa", "state": "CA"},
    {"name": "Ziba Foods", "website": "http://www.zibafoods.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Lewes", "state": "DE"},
    {"name": "Demeine Estates", "website": "http://www.demeineestates.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Saint Helena", "state": "CA"},
    {"name": "Know Your Body Best", "website": "https://www.bodybest.com", "industry": "Retail", "subindustry": "Vitamins, Supplements & Health Stores", "city": "Toronto", "state": "ON"},
    {"name": "Master Roll", "website": "http://master-roll.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "La Porte", "state": "IN"},
    {"name": "Bluegrass Biomedical, Inc.", "website": "http://www.bgbky.com", "industry": "Retail", "subindustry": "Vitamins, Supplements & Health Stores", "city": "Danville", "state": "KY"},
    {"name": "Meltar Supply", "website": "http://meltarsupply.com", "industry": "Retail", "subindustry": "Home Improvement & Hardware Retail", "city": "Donald", "state": "OR"},
    {"name": "REP Provisions LLC", "website": "http://www.repprovisions.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Tulsa", "state": "OK"},
    {"name": "X-Biomedical", "website": "http://www.x-biomedical.com", "industry": "Retail", "subindustry": "Vitamins, Supplements & Health Stores", "city": "Wayne", "state": "PA"},
    {"name": "Goose Ridge Vineyards", "website": "https://www.gooseridge.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Richland", "state": "WA"},
    {"name": "Jack Francis Foods, LLC", "website": "http://www.jackfrancisfoods.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Ferndale", "state": "WA"},
    {"name": "Life Raft Treats", "website": "http://liferafttreats.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Charleston", "state": "SC"},
    {"name": "Manus Neurodynamica Limited (Horao Neurolabs)", "website": "http://www.manusneuro.com", "industry": "Retail", "subindustry": "Vitamins, Supplements & Health Stores", "city": "Palo Alto", "state": "CA"},
    {"name": "Italia Foods, Inc.", "website": "http://www.italiafoods.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Schaumburg", "state": "IL"},
    {"name": "JTB Distributors", "website": "http://www.jtbdistributors.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Napa", "state": "CA"},
    {"name": "Carbone Fine Food", "website": "http://www.carbonefinefood.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "New York City", "state": "NY"},
    {"name": "Zenbuild", "website": "http://www.zenbuild.com", "industry": "Retail", "subindustry": "Home Improvement & Hardware Retail", "city": "Chattanooga", "state": "TN"},
    {"name": "Blenz Coffee", "website": "http://www.blenz.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Nelson", "state": "BC"},
    {"name": "Top Glaciers", "website": "http://topglaciers.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Montréal", "state": "QC"},
    {"name": "Pluck Tea", "website": "http://www.pluckteas.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "TORONTO", "state": "ON"},
    {"name": "Tosi", "website": "http://www.tosi.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Anaheim", "state": "CA"},
    {"name": "Borga Steel", "website": "http://www.borgasteel.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "Fowler", "state": "CA"},
    {"name": "Spirits On Ice", "website": "http://www.spiritsonice.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Lebanon", "state": "OH"},
    {"name": "Crucible Construction", "website": "http://www.crucibleconstruction.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Daphne", "state": "AL"},
    {"name": "Union Square Donuts", "website": "http://www.unionsquaredonuts.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "Somerville", "state": "MA"},
    {"name": "Boba Guys", "website": "http://www.bobaguys.com", "industry": "Retail", "subindustry": "Grocery Retail", "city": "San Francisco", "state": "CA"},
    {"name": "Port City Java", "website": "http://www.portcityjava.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "", "state": "NC"},
    {"name": "ArborWind", "website": "http://www.arborwind.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "Ann Arbor", "state": "MI"},
    {"name": "Oro Chocolate", "website": "http://www.orochocolate.com", "industry": "Manufacturing", "subindustry": "Food & Beverage", "city": "Chicago", "state": "IL"},
    {"name": "USM Americas", "website": "https://usm-americas.com", "industry": "Manufacturing", "subindustry": "Industrial Machinery & Equipment", "city": "", "state": "QC"},
    {"name": "National Ramp", "website": "http://www.nationalramp.com", "industry": "Manufacturing", "subindustry": "Building Materials", "city": "Valley Cottage", "state": "NY"},
    {"name": "Nutrition for Longevity Inc.", "website": "http://www.nutritionforlongevity.com", "industry": "Retail", "subindustry": "Vitamins, Supplements & Health Stores", "city": "Randolph", "state": "NJ"},
]
